version: '3'
services:
  vote-redis:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: vote-redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  vote-app:
    build: ./vote
    image: edevopstalk.azurecr.io/voteapp:latest
    container_name: vote-app
    environment:
      REDIS: vote-redis
    ports:
        - "8080:80"